#Docker compose file
services:
  ngnix:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "8001:80"
    environment:
      - "WEB_KEY=webkey"
    networks:
      - "my-net"
    restart: "no"                 #always, on-failure:3, unless-stopped
    depends_on:
      - "apache"

  apache:
    image: "httpd:latest"
    ports:
      - "8002:80"
    networks:
      - "my-net"
    deploy:
      resources:
        limits:
          memory: "4g"
          cpus: "2"
        reservations:
          memory: "2g"
          cpus: "1"
    command: ["httpd-foreground"]
    
networks:
  my-net:
    driver: "bridge"
