//JenkinsFile
pipeline {
    agent any                                               //none
    // agent {
    //     label "node1"
    // }
    // agent {
    //     node {
    //         label "node1"
    //         customWorkspace "/var/lib/jenkins"
    //     } 
    // }

    options {
        buildDiscarder (logRotator (numToKeepStr: "3"))
        disableConcurrentBuilds (abortPrevious: false)      //true
        quietPeriod (10)
        retry (5)
        timeout (time: 5, unit: "MINUTES")
        timestamps ()
    }

    environment {
        f = "false"
        id = "100"
        name = "sudeep"
    }

    tools {
        maven "maven"                                       //jdk, gradle
    }

    parameters {
        booleanParam (name: "Boolean", description: "Boolean", defaultValue: false)
        choice (name: "Choice", description: "Choice", choices: ["html", "css", "javascript"])
        password (name: "Password", description: "Password", defaultValue: "typescript")
    }

    triggers {
        cron ("* * * * *")
        pollSCM ("* * * * *")
        upstream (
            upstreamProjects: "project1, project2",
            threshold: hudson.model.Result.SUCCESS          //UNSTABLE, FAILURE, ABORTED
        )
    }

    stages {
        stage ("A") {
            // agent
            // options
            // environment
            // tools

            when {
                not {
                    environment (name: "true", value: "${env.f}")
                }
                allOf {
                    equals (expected: "false", actual: "${params.Boolean}")
                    expression {
                        if ("${env.id}" == "100" && "${params.Choice}" == "html")
                        return true
                        else
                        return false
                    }
                }
                anyOf {
                    branch "main"
                    tag "v2"
                    triggeredBy "SCMTrigger"                //TimerTrigger, BuildUpstreamCause
                }
            }

            steps {
                git (branch: "main", credentialsId: "odp-github-repo", url: "https://github.com/1xtel/ODP.git")
                dir ("Jenkins/configs") {
                    echo pwd()
                }
            }
            // post
        }

        stage ("B") {
            stages {
                stage ("B.a") {
                    steps { echo "${env.name}" }
                }
                stage ("B.b") {
                    steps { echo "${params.Password}" }
                }
            }
        }

        stage ("C") {
            parallel {
                stage ("C.a") {
                    steps { sh "echo Jenkins" }
                }
                stage ("C.b") {
                    steps { sh "touch Jenkins" }
                }
            }
        }
    }

    post {
        success {
            sleep (time: 5, unit: "SECONDS")                //unsuccessful, failure, unstable, aborted
                                                            //always, changed, fixed, regression, cleanup

            script {
                def user = input (id: "Input", message: "Input", ok: "Button", parameters: [
                    string (name: "String", description: "String", defaultValue: "python"),
                    text (name: "MultiLineString", description: "MultiLineString", defaultValue: "c\nc++\njava")
                ])
                echo "${user.String}"
                echo "${user.MultiLineString}"
            }
        }
    }
}